# .azure-pipelines.yml
trigger:
  - main

pool:
  vmImage: 'ubuntu-latest' # You can change this to a different agent if needed (e.g., 'windows-latest')

steps:
  - script: |
      echo "The source branch is: $(Build.Repository.Name)"
      echo "The source branch is: $(Build.SourceBranch)"
      echo "The source branch is: $(Build.Repository.Uri)"
      echo "The source branch is: $(Build.Repository.LocalPath)"
    displayName: 'Echo Source Branch'

  - script: |
      echo "Running some build task"
      # Add your build or test commands here
    displayName: 'Build task'
