# .azure-pipelines.yml
trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest' # You can change this to a different agent if needed (e.g., 'windows-latest')

steps:
  - task: Checkout@1
    displayName: 'Checkout code'

  - script: |
      echo "The source branch is: $(Agent.BuildDirectory)"
    displayName: 'Echo Source Branch'

  - script: |
      echo "Running some build task"
      # Add your build or test commands here
    displayName: 'Build task'
